### ISSUE TITLE
Použít konstantu na mobile device width - je totiž možné, že to budeš používat častěji

### ISSUE THREAD

**Issue by alena424** [katykola/trip-inspirations#1]
https://github.com/katykola/trip-inspirations/blob/d554484ed888f0e64ffc8e6253ca3abf6d75c3c6/src/App.tsx#L25C39-L25C53

const smallScreenBreakpoint = XXX // tohle ještě nejlépe aby bylo zvlášť v souboru v breakpoints.ts pokud bys takových konstant měla více

const isMobile = useMediaQuery(smallScreenBreakpoint);

**Comment by katykola** [comment]
Implemetováno :)
